module.exports = {
  arrowParens: 'always',
  endOfLine: 'lf',
  jsxSingleQuote: true,
  printWidth: 120,
  quoteProps: 'consistent',
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  bracketSpacing: true,
  semi: true,
  useTabs: false,
  bracketSameLine: false,
  proseWrap: 'preserve',
};
