name: PR 요청 Slack 전송

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: send pr to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.CODE_REVIEW_SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: 'github_frontend'
          SLACK_USERNAME: 'Monolith_코드리뷰_요청'
          SLACK_ICON: ':kakaostyle'
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: "리뷰 한번만 부탁드립니다. 🙏\n<${{ github.event.pull_request.html_url }}|PR 확인하기>"
          SLACK_FOOTER: ''
          MSG_MINIMAL: 'true'
