name: PR 요청 Slack 전송

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: send pr to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: "github_frontend"
          SLACK_USERNAME: "Monolith_코드리뷰_요청"
          SLACK_ICON_EMOJI: ":zig-zag"
          SLACK_COLOR: "good"
          SLACK_TITLE: "${{ github.event.pull_request.title }}"
          SLACK_MESSAGE: "리뷰 부탁드립니다. 🙏"
          SLACK_FOOTER: ""
          MSG_MINIMAL: "true"
