name: token test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '30 22 * * 1-5'

env:
  TARGET_BRANCH: main
  ALPHA_BRANCH: alpha
  SLACK_CHANNEL: dev_deploy_zigzag
  LABEL_NAME: alpha

jobs:
  sync-alpha:
    runs-on: ubuntu-latest

    steps:
      - name: Access Secrets
        run: |

      - name: Access Secrets2
        run: |
          echo "Secret Token : ${{ secrets.PACKAGE_PUBLISH_KEY_GITHUB }}"
      
      - name: Access Secrets3
        run: |
          echo "Secret Token : ${{ secrets.PACKAGE_PUBLISH_KEY_NPM }}"
    